# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69f9a16f36599697b4bf8814f709dd16e5237a9b128fa4010613000ccfe17d98d35269618d3e20235e95af2e4cf095ba5c8c6d8f6a883269baadd40ba227731e

test:
  secret_key_base: 6b2535d195756ab9f98c51e7ead1b76ceefdfe46c7c56f107b9d9bcbc4ae34523f946a3f61863b7319b24b613af18b1c5b864ff828c341565c07cc5b03665cef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
